<?php

/**
 * Implementation of hook_node_info().
 */
function ubox_node_info() {
  $items = array(
    'ubox' => array(
      'name' => t('Userfriendly Box'),
      'module' => 'features',
      'description' => t('A userfriendly way to generate boxes with drupal content'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'has_body' => '1',
      'body_label' => t('Custom text'),
      'min_word_count' => '0',
      'help' => '',
    ),
  );
  return $items;
}
