<?php
/**
 * Implementation of hook_wysiwyg_include_directory().
 *
 * This tells the Wysiwyg module to search within the 'plugins' directory for
 * Wysiwyg plugins.
 *
 * @param String $type
 * The type of plugin being checked. One of:
 * - editor: for WYSIWYG editors such as TinyMCE, CKEditor, Nice Edit, etc.
 * - plugin: for toolbar buttons such as bold, add-image, strike-through, etc.
 *
 * @return String
 * The path to the plugin directory (relative to this module). This is usually
 * simply the plugin-type: e.g. "plugin" or "editor".
 */
function wysiwyg_richmedia_wysiwyg_include_directory($type) {
  return $type;
}

function wysiwyg_richmedia_form_alter(&$form, &$form_state, $form_id) {
  /* Attach jQuery UI Dialog to node forms. */
  if (isset($form['type']['#value']) && $form_id == $form['type']['#value'] . '_node_form') {
    $form['#after_build'][] = 'wysiwyg_richmedia_build_after';
  }
}

function wysiwyg_richmedia_init(){
  drupal_add_css(drupal_get_path('module', 'wysiwyg_richmedia') . '/plugins/slideshow/wysiwyg_richmedia_slideshow.css');
}

function wysiwyg_richmedia_build_after($form_element, &$form_state) {

  /* Add Javascript. */
  jquery_ui_add('ui.dialog');
  return $form_element;
}

/**
 * Implementation of hook_filter().
 */
function wysiwyg_richmedia_filter($op, $delta = 0, $format = -1, $text = '') {
  switch ($op) {
    case 'list':
      return array(t('Wysiwyg Richmedia'));
    case 'description':
      return t('Allows content to be submitted using Wysiwyg Richmedia, a simple way to implement richmedia like slideshow or lightboxs.');
    case 'process':
      return _wysiwyg_richmedia_process($text, $format);
    default:
      return $text;
  }
}

/**
 * Filter process callback.
 */
function _wysiwyg_richmedia_process($text, $format) {
  if (!empty($text)) {
    // Filter wysiwyg_richmedia_slideshow
    preg_match_all("#<!--wysiwyg_richmedia_slideshow-[0-9]+\\[(.+?)\\]--\\>#", $text, $matches);
    
    for($i = 0; $i < sizeof($matches[1]); $i=$i+2){
    	// There is a bug that duplicate comments.
    	// This remove one
    	$text = str_replace($matches[0][$i].$matches[0][$i], $matches[0][$i], $text);
    	
    	$datas = array();
    	$match = $matches[1][$i];
	    
	    // Retrieve datas per field
	    $allDatas = explode("|",$match);
	    foreach($allDatas as $allData){
	    	$datasQuoted = explode(',', $allData);
	    	$datasClean = array();
	    	foreach($datasQuoted as $datasQ){
	    		$datasClean[] = substr($datasQ, 1, -1);
	    	}
	    	$datas[] = $datasClean;
	    }
	    
	    $items = "";
	    
	    foreach($datas as $data){
		    // Template data - src image, alt image, description text, href link
		    $items .= theme('wysiwyg_richmedia_slideshow-item', $data[0], $data[1], $data[2], $data[3]);
	    }
	    
	    // Template Slideshow
	    $slideshow = theme('wysiwyg_richmedia_slideshow', $items);
	    //dsm($text);
	    // Replace comments by templates
	    $text = str_replace($matches[0][$i], $slideshow, $text);
	  }

  }

  return $text;
}

/**
 * Implementation of hook_theme().
 */
function wysiwyg_richmedia_theme($existing, $type, $theme, $path) {
  return array(
    'wysiwyg_richmedia_slideshow-item' => array(
      'arguments' => array('src' => NULL, 'alt' => NULL, 'text' => NULL, 'href' => NULL),
      'template' => 'wysiwyg_richmedia_slideshow-item',
    ),
    'wysiwyg_richmedia_slideshow' => array(
      'arguments' => array('items' => NULL),
      'template' => 'wysiwyg_richmedia_slideshow',
    ),

  );
}