<?php

/**
 * Implementation of hook_form_alter().
 */
function cdt_formalter_form_alter(&$form, $form_state, $form_id) {
  
  //Dans tout le site pour les exposed forms, si le libellé est "Commune", on modifie "Tous" par "Toutes"
  if($form_id=="views_exposed_form"){
  	
  	
  	
  	//FORMULAIRES DE RECHERCHE DANS LES FLUX
  	if($form['submit']['#id']=='edit-submit-hqflux-search-influx'){
  	
  		//Changement de "Appliquer" en "Rechercher" dans les recherche de flux
  		$form['submit']['#value']=t('Launch search');
  		
  		//Changement de "- Tous -" en "- Toutes -" pour le champ commune
  		if(isset($form['commune']) && $form['commune']['#type']=='select' && $form['commune']['#default_value']=='All'){
  			$form['commune']['#options']['All']='- '.t('Any city').' -';
  		}
  		
  	}
  	
  	
  }
  
}
