<?php

include_once('feature_content_pages.features.inc');

/**
 * Implements hook_views_query_alter().
 *
 * Move arguments into an "OR" group.
 */
function feature_content_pages_views_query_alter(&$view, &$query){
  if ($view->name == 'gnova_href_backref_primary' || $view->name == 'gnova_href_backref_teaser') {
    $group = $query->set_where_group('OR', 'parents-group', 'where');
    $query->add_where($group, $query->where[0]['clauses'][1], $query->where[0]['args'][0]);
    $query->add_where($group, $query->where[0]['clauses'][2], $query->where[0]['args'][1]);
    unset($query->where[0]['clauses'][1]);unset($query->where[0]['args'][0]);
    unset($query->where[0]['clauses'][2]);unset($query->where[0]['args'][1]);

    $query->set_distinct();
  }
}

/**
 * Implements hook_views_pre_build().
 *
 * Duplicate the first argument.
 */
function feature_content_pages_views_pre_build(&$view) {
  if ($view->name == 'gnova_href_backref_primary' || $view->name == 'gnova_href_backref_teaser') {
    $view->args[] = $view->args[0];
  }
}
