<?php
function cdt_sitemap_menu(){
  $items = array();

  $language_list = language_list('language');

	$items['sitemap'] = array(
    'title' => 'Sitemap',
    'page callback' => 'cdt_sitemap_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  foreach($language_list as $lang_key => $lang) {
    $alias_sitemap = t('Sitemap', array(), $lang_key);

    $existing_path = drupal_lookup_path('alias', 'sitemap', $lang_key);
    $new_path = cdt_sitemap_cleanstring($alias_sitemap);

    if(!$existing_path || ( $existing_path != FALSE && $existing_path != $new_path)){
      path_set_alias('sitemap', $new_path, NULL, $lang_key);
    }
  }

  return $items;
}

function cdt_sitemap_theme(){
  $themes = array(
    'cdt_sitemap_page' => array(
      'arguments' => array('sitemap' => NULL, 'title' => NULL),
      'template' => 'cdt_sitemap',
      'path' => drupal_get_path('module', 'cdt_sitemap') . '/templates',
    )
  );
  return $themes;
}

function cdt_sitemap_page(){
 	drupal_set_title(t('Sitemap'));

  $primary_links = menu_tree_page_data('primary-links');

  $items = cdt_sitemap_generate_from_menu($primary_links);
  $content = theme('item_list', $items);

  $output = theme('cdt_sitemap_page', $content, t('Sitemap'));

  return $output;
}

function cdt_sitemap_generate_from_menu($tree, $level=0){
  global $language;
  
  $items = array();
  foreach($tree as $item){
    // On ne prend que les elements de la langue en cours
    if(!$item['link']['hidden'] && ($item['link']['options']['langcode'] == $language->language || $item['link']['options']['langcode'] == '')){
	    // On récupère les enfants de l'éléments en cours
	    $children = array();
	    if(!empty($item['below'])){
	      $children = cdt_sitemap_generate_from_menu($item['below'], $level+1);
	    }
	    // si type de contenu hierarchique, on récupère les enfants
	    $nid = preg_replace('/node\/([0-9]+)/', '$1', $item['link']['link_path']);
	
	    $path = $item['link']['link_path'];
	
	    if(preg_match('/^[0-9]+$/', $nid)){
	      $children += cdt_sitemap_generate_from_nid($nid, $level+1);
	      $path = drupal_get_path_alias('node/'.$nid, $language->language);
	    }
	
	    // Titre + lien de l'item + ses enfants
	    $items[] = array(
	      'data' => l(t($item['link']['link_title']), $path),
	      'children' => $children,
	      'class' => 'level-'.$level,
	    );
	  }
  }

  return $items;
}

function cdt_sitemap_generate_from_nid($nid, $level=0){
  global $language;
  $items = array();
  $children = array();

  $sql = "SELECT n.nid FROM {node} n INNER JOIN {content_type_hqitem} cth ON cth.nid=n.nid WHERE n.status = 1 AND cth.field_hqitem_parent_nid = %d AND (n.language = '%s' OR n.language = '')";
  $request = db_query($sql, $nid, $language->language);

  while($result = db_fetch_object($request)){

    $children = cdt_sitemap_generate_from_nid($result->nid, $level+1);

    $node = node_load($result->nid);

    $items[] = array(
      'data' => l($node->title, drupal_get_path_alias('node/'.$node->nid, $language->language)),
      'children' => $children,
      'class' => 'level-'.$level,
    );
  }

  return $items;
}



function cdt_sitemap_cleanstring($s) {

  module_load_include('inc', 'pathauto', 'pathauto');
  return strtolower(pathauto_cleanstring($s));

} // cdt_sitemap_cleanstring