<?php

/**
 * Implementation of hook_menu().
 */
function flux_redirect_menu() {
  $items = array();

  $items['techredirect/%'] = array(
    'page callback' => 'flux_technical_redirect',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  return $items;
}

function flux_technical_redirect($offerid){
	if($offerid && strlen($offerid)>0){
		$res = db_query("SELECT * FROM {flux_nid_id} WHERE ficheid='%s'", $offerid);
		$res = db_fetch_object($res);
		if($res){
			drupal_goto('node/'.$res->nid, NULL, NULL, NULL, 301);
			return;
		}
	}
	drupal_goto('');
	return;
}

/**
 * Implementation of hook_nodeapi().
 * Act on nodes defined by other modules.
 *
 * @param &$node
 *   The node the action is being performed on.
 * @param $op
 *   What kind of action is being performed.
 * @param $a3
 *   - For "view", passes in the $teaser parameter from node_view().
 *   - For "validate", passes in the $form parameter from node_validate().
 * @param $a4
 *   - For "view", passes in the $page parameter from node_view().
 * @return
 *   This varies depending on the operation.
 *   - The "presave", "insert", "update", "delete", "print" and "view"
 *     operations have no return value.
 *   - The "load" operation should return an array containing pairs
 *     of fields => values to be merged into the node object.
 */
function flux_redirect_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'insert':
    case 'update':
    	if($node->nid && $node->field_fl_techid_tx[0]['value']){
    		flux_technical_addorupdate($node->nid, $node->field_fl_techid_tx[0]['value']);
    	}
    break;
    case 'delete':
    	if($node->nid && $node->field_fl_techid_tx[0]['value']){
    		db_query("DELETE FROM {flux_nid_id} WHERE nid=%d", $node->nid);
    	}
    break;
  }
}

function flux_technical_addorupdate($nid, $ficheid){
	$q = db_query("SELECT count(*) AS nb FROM {flux_nid_id} WHERE ficheid='%s' OR nid=%d", $ficheid, $nid);
	if($res = db_fetch_array($q)){
		if($res['nb'] && $res['nb']>0){
			$res = db_query("SELECT * FROM {flux_nid_id} WHERE ficheid='%s' OR nid=%d", $ficheid, $nid);
			$item = db_fetch_object($res);
			if($item->nid==intval($nid)){
				db_query("UPDATE {flux_nid_id} SET nid=%d WHERE ficheid='%s'", $item->ficheid);
			}elseif($item->ficheid==$ficheid){
				db_query("UPDATE {flux_nid_id} SET ficheid='%s' WHERE nid=%d", $item->nid);
			}
			return;
		}
	}
		db_query("INSERT INTO {flux_nid_id} (nid, ficheid) VALUES (%d, '%s')", $nid, $ficheid);
}