<?php

/**
 * Implements hook_translation_link_alter
 */
function homehead_translation_link_alter(&$links, $path){
	
	
	if(module_exists('domain')){
	
		global $_domain;
		
		
		$languages = language_list('enabled');
		$languages = $languages[1];
		
		
		foreach($languages as $code => $lang){
			
			if(isset($links[$code])){
				
				if($_domain['domain_id']==0){
					if(strlen($lang->domain)>0){
						$links[$code]['href'] = $lang->domain.base_path().($path != '<front>' ? $links[$code]['href'] : '');
					}else{
						$links[$code]['href'] = $_domain['path'].($path != '<front>' ? $links[$code]['href'] : '');
					}
				}
				else{
					$links[$code]['href'] = ($path != '<front>' ? $links[$code]['href'] : '');
				}		
			}
		}		
	}
}