<?php
function export_reports_menu(){
  $items = array();

  $items['admin/reports/search/csv'] = array(
    'page callback' => 'export_reports_dblog_top_export',
    'page arguments' => array('search', 'csv'),
    'access arguments' => array('access site reports'),
    'file' => 'export_reports.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/reports/search/xls'] = array(
    'page callback' => 'export_reports_dblog_top_export',
    'page arguments' => array('search', 'xls'),
    'access arguments' => array('access site reports'),
    'file' => 'export_reports.admin.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function export_reports_menu_alter(&$items){
  $items['admin/reports/search']['page callback'] = 'export_reports_dblog_top';
  $items['admin/reports/search']['page arguments'] =  array('search');
  $items['admin/reports/search']['file'] = 'export_reports.admin.inc';
  $items['admin/reports/search']['file path'] = drupal_get_path('module', 'export_reports');
}